// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVPl2pWNP54CFtZ_vc5-loT2jF9QahqBk',
    appId: '1:488390643778:web:032956d19a137f3baf5ddb',
    messagingSenderId: '488390643778',
    projectId: 'flutter-note-1813e',
    authDomain: 'flutter-note-1813e.firebaseapp.com',
    storageBucket: 'flutter-note-1813e.firebasestorage.app',
    measurementId: 'G-JZPW5NF1F5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3Eg0ZsSlqjTrup5TR2Tqbiq-fPxFcVQg',
    appId: '1:488390643778:android:50057c23635c9bfaaf5ddb',
    messagingSenderId: '488390643778',
    projectId: 'flutter-note-1813e',
    storageBucket: 'flutter-note-1813e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrHBWmITh77GHOjwjEczQ1XwWNzCffca0',
    appId: '1:488390643778:ios:a225684356c22694af5ddb',
    messagingSenderId: '488390643778',
    projectId: 'flutter-note-1813e',
    storageBucket: 'flutter-note-1813e.firebasestorage.app',
    androidClientId: '488390643778-9l4etutbgc3baqugvuksrspr56md0aea.apps.googleusercontent.com',
    iosClientId: '488390643778-82ptt1cmb1sbqhs4o7p6er13ldnslnvq.apps.googleusercontent.com',
    iosBundleId: 'com.example.inventoryFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrHBWmITh77GHOjwjEczQ1XwWNzCffca0',
    appId: '1:488390643778:ios:a225684356c22694af5ddb',
    messagingSenderId: '488390643778',
    projectId: 'flutter-note-1813e',
    storageBucket: 'flutter-note-1813e.firebasestorage.app',
    androidClientId: '488390643778-9l4etutbgc3baqugvuksrspr56md0aea.apps.googleusercontent.com',
    iosClientId: '488390643778-82ptt1cmb1sbqhs4o7p6er13ldnslnvq.apps.googleusercontent.com',
    iosBundleId: 'com.example.inventoryFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVPl2pWNP54CFtZ_vc5-loT2jF9QahqBk',
    appId: '1:488390643778:web:c632dcffd2beb355af5ddb',
    messagingSenderId: '488390643778',
    projectId: 'flutter-note-1813e',
    authDomain: 'flutter-note-1813e.firebaseapp.com',
    storageBucket: 'flutter-note-1813e.firebasestorage.app',
    measurementId: 'G-QTKZ0X6ETP',
  );

}